### ISSUE TITLE
Create documentation/examples for programmatically creating/importing quizzes

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/quiz_service#24]
## Description
~Create json schema and an HTTP endpoint to import quizzes~
Give Niklas a guide how to use the API to import quizzes

## Acceptance Criteria
- [ ] quizzes can be imported

**Comment by PaulBredl** [comment]
we disussed with niklas that a description of the api and tutorial how to do it is sufficient

**Comment by PaulBredl** [comment]
@LG1401 should be probably done this sprint with 1 SP
